#!/bin/bash

# disables mysql-server prompt for password
export DEBIAN_FRONTEND=noninteractive

if [[ $# != 1 ]] ; then
	echo "Usage: $0 package-list" 1>&2
	exit 1
fi

pkg_list=$1

echo "updating apt-get"
apt-get update
apt-get -y upgrade all

for pkg in `cat $pkg_list` ; do
	echo "install $pkg"
	apt-get -y install $pkg
done
apt-get remove -y ispell

for pkg in `cat $pkg_list` ; do
	echo "reinstall $pkg"
	apt-get -y install $pkg
	if [[ $? -ne 0 ]] ; then
		echo "Failure installing $pkg" 1>&2
	fi
done
