#!/bin/bash

if [[ $# != 1 ]] ; then
	echo "Usage: $0 package-list" 1>&2
	exit 1
fi

pkg_list=$1
# kludge to get emacs23, firefox working
export LANG=C
apt-get remove -y dictionaries-common ispell
apt-get install -y dictionaries-common ispell

for pkg in `cat $pkg_list` ; do
	echo "install $pkg"
	apt-get -y install $pkg
	if [[ $? -ne 0 ]] ; then
		echo "Failure installing $pkg" 1>&2
	fi
done
