install.packages ("methods", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("utils", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("boot", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("class", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("cluster", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("codetools", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("foreign", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("KernSmooth", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("lattice", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("MASS", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("Matrix", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("mgcv", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("nlme", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("nnet", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("rpart", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("spatial", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("survival", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("randomForest", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("optparse", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("vegan", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("ape", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("MASS", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("klaR", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("RJSONIO", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("matlab", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("ecodist", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("Cairo", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("gplots", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("scatterplot3d", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("WGCNA", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("igraph", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("stats", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("ggplot2", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("RCurl", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("devtools", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("RSQLite", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("rJava", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("irr", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("amap", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("lars", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("fields", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
install.packages ("Hmisc", repos = "http://cran.wustl.edu", lib = "[% rlib %]")
source ("http://bioconductor.org/biocLite.R")
biocLite ("Biobase")
biocLite ("edgeR")
biocLite ("limma")
biocLite ("pcaMethods")
biocLite ("qvalue")
biocLite ("impute")
