install.packages ("randomForest", repos = "http://cran.wustl.edu")
install.packages ("optparse", repos = "http://cran.wustl.edu")
install.packages ("vegan", repos = "http://cran.wustl.edu")
install.packages ("ape", repos = "http://cran.wustl.edu")
install.packages ("MASS", repos = "http://cran.wustl.edu")
install.packages ("klaR", repos = "http://cran.wustl.edu")
install.packages ("RJSONIO", repos = "http://cran.wustl.edu")
install.packages ("matlab", repos = "http://cran.wustl.edu")
install.packages ("ecodist", repos = "http://cran.wustl.edu")
install.packages ("Cairo", repos = "http://cran.wustl.edu")
install.packages ("gplots", repos = "http://cran.wustl.edu")
source ("http://bioconductor.org/biocLite.R")
biocLite ("Biobase")
biocLite ("edgeR")
biocLite ("limma")
biocLite ("pcaMethods")
biocLite("qvalue")
