install.packages ("boot", repos = "http://cran.wustl.edu")
install.packages ("class", repos = "http://cran.wustl.edu")
install.packages ("cluster", repos = "http://cran.wustl.edu")
install.packages ("codetools", repos = "http://cran.wustl.edu")
install.packages ("foreign", repos = "http://cran.wustl.edu")
install.packages ("KernSmooth", repos = "http://cran.wustl.edu")
install.packages ("lattice", repos = "http://cran.wustl.edu")
install.packages ("MASS", repos = "http://cran.wustl.edu")
install.packages ("Matrix", repos = "http://cran.wustl.edu")
install.packages ("mgcv", repos = "http://cran.wustl.edu")
install.packages ("nlme", repos = "http://cran.wustl.edu")
install.packages ("nnet", repos = "http://cran.wustl.edu")
install.packages ("rpart", repos = "http://cran.wustl.edu")
install.packages ("spatial", repos = "http://cran.wustl.edu")
install.packages ("survival", repos = "http://cran.wustl.edu")
install.packages ("randomForest", repos = "http://cran.wustl.edu")
install.packages ("optparse", repos = "http://cran.wustl.edu")
install.packages ("vegan", repos = "http://cran.wustl.edu")
install.packages ("ape", repos = "http://cran.wustl.edu")
install.packages ("MASS", repos = "http://cran.wustl.edu")
install.packages ("klaR", repos = "http://cran.wustl.edu")
install.packages ("RJSONIO", repos = "http://cran.wustl.edu")
install.packages ("matlab", repos = "http://cran.wustl.edu")
install.packages ("ecodist", repos = "http://cran.wustl.edu")
install.packages ("Cairo", repos = "http://cran.wustl.edu")
install.packages ("gplots", repos = "http://cran.wustl.edu")
install.packages ("scatterplot3d", repos = "http://cran.wustl.edu")
install.packages ("WGCNA", repos = "http://cran.wustl.edu")
install.packages ("igraph", repos = "http://cran.wustl.edu")
install.packages ("stats", repos = "http://cran.wustl.edu")
source ("http://bioconductor.org/biocLite.R")
biocLite ("Biobase")
biocLite ("edgeR")
biocLite ("limma")
biocLite ("pcaMethods")
biocLite ("qvalue")
biocLite ("impute")

